version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend_api:8080/users
    networks:
      - backend_network

networks:
  backend_network:
    external: true